backend/controllers/BadgeController.php
<?php

namespace backend\controllers;

use backend\controllers\SiteController;
use kartik\mpdf\Pdf;

class BadgeController extends SiteController
{	
    public function actionBadgePrintView() {
    // get your HTML raw content without any layouts or scripts
        //return $this->render('badge-print-view');
        $content = $this->renderPartial('_badge-print-view');
        
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_BLANK, 
            // A4 paper format
            'format' => Pdf::FORMAT_A4, 
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT, 
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER, 
            // your html content input
            'content' => $content, 
            'marginTop'=>0,
            'marginLeft'=>0,
            'marginRight'=>0,
            'marginBottom'=>0,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting 
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}', 
             // set mPDF properties on the fly
            'options' => ['title' => 'AGC Range Badge'],
             // call mPDF methods on the fly
            'methods' => [ 
                'SetHeader'=>['Powered By itekk.us'], 
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);
        
        // return the pdf output as per the destination setting
        return $pdf->render(); 
    }
    
	public function actionCreate() {
		$model = new \backend\models\Badges();
		return $this->render('_create',[
			'model' => $model
		]);
	}

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionUpdate()
    {
       $model = new \backend\models\Badges();
        return $this->render('_update',[
            'model' => $model
        ]);
    }

    public function actionAdminFunction() {

        return $this->render('adminMenu');
    }
    public function actionClubNameLookUp() {
        return $this->render('club-name-look-up');
    }
    public function actionClubNameCreate() {
        $model = new \backend\models\Badges();
        return $this->render('create-club-name',['model'=>$model]);
    }

    public function actionClubNameEdit() {
        $model = new \backend\models\Badges();
        return $this->render('edit-club-name',['model'=>$model]);
    }

    public function actionBrowsWorkCredits() {
        return $this->render('brows-credit');
    }

    public function actionWorkCreditMenu() {
        return $this->render('work-credit-menu');
    }

    public function actionWorkCreditTransfer() {

         $model = new \backend\models\Badges();
        return $this->render('work-credit-transfer',[
            'model' => $model
        ]);

        
    }

    public function actionWorkCreditEntry() {
        $model = new \backend\models\Badges();
        return $this->render('work-credit-entry',[
            'model' => $model
        ]);
         
    }


    public function actionUsersIndex() {

        return $this->render('users-index');
    }

    public function actionCreateUser() {
        $model = new \backend\models\Badges();
        return $this->render('create-user',[
            'model' => $model
            ]);
    }

    public function actionEditUser() {
        $model = new \backend\models\Badges();
        return $this->render('edit-user',[
            'model' => $model
            ]);
    }

     public function actionViewUser() {
        $model = new \backend\models\Badges();
        return $this->render('view-user',[
            'model' => $model
            ]);
    }


    





    

}

backend/controllers/BadgesController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Badges;
use backend\models\search\BadgesSearch;
use backend\models\BadgeSubscriptions;
use backend\models\WorkCreditTransactions;
use backend\models\MembershipType;
use backend\models\search\BadgeCertificationSearch;
use backend\models\search\WorkCreditTransactionsSearch;
use backend\models\search\BadgeSubscriptionsSearch;
use backend\models\search\PostPrintTransactionsSearch;
use backend\models\Clubs;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\helpers\ArrayHelper;
use kartik\mpdf\Pdf;
use backend\controllers\AdminController;
use backend\models\WorkCredits;
use backend\models\search\WorkCreditsSearch;
use backend\models\FeesStructure;
use backend\models\BadgeCertification;
use kartik\export\ExportMenu;
use kartik\grid\GridView;


/**
 * BadgesController implements the CRUD actions for Badges model.
 */
class BadgesController extends AdminController
{
    /**
     * @inheritdoc
     */
    public $enableCsrfValidation = false;

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Badges models.
     * @return mixed
     */

    /*public function actionTest() {

        $searchModel = new BadgesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('_test',[
                'searchModel'=> $searchModel,
                'dataProvider'=> $dataProvider,
            ]);





    }*/



    public function actionViewCertificate($membership_id,$view_id) {
       
       $badgesModel = Badges::findOne($membership_id);
       $certificationModel = BadgeCertification::findOne($view_id);

        return $this->render('view-certificate',[
            'badgeModel'=> $badgesModel,
            'certificationModel'=> $certificationModel,
        ]);
    }

    public function actionViewCertificationsList($id) {
        $searchModel = new BadgeCertificationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['badge_number'=>$id]);
        $dataProvider->query->orderBy(['id' => SORT_DESC]);

        return $this->render('view-certifications-list',[
            'model'=>$this->findModel($id),
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

     public function actionUpdateCertificate($membership_id,$view_id) {
       
       $badgesModel = Badges::findOne($membership_id);
       $certificationModel = BadgeCertification::findOne($view_id);
       if($certificationModel->load(Yii::$app->request->post())) {
            $certificationModel->updated_at = $this->getNowTime();
            $certificationModel->save(false);
            Yii::$app->getSession()->setFlash('success', 'Certificate has been edited');
            
       }

        return $this->render('update-certificate',[

            'badgeModel'=> $badgesModel,
            'certificationModel'=> $certificationModel,
        ]);
    }

    public function actionDeleteCertificate($membership_id,$view_id) {
        $certificationModel = BadgeCertification::findOne($view_id);
        if($certificationModel->badge_number==$membership_id) {
            $certificationModel->delete();
            Yii::$app->getSession()->setFlash('success', 'Certificate has been deleted');
            return $this->redirect(['badges/view-certifications-list','id'=>$membership_id]); 
        }
        //echo'<pre>'; print_r($certificationModel); die();

    }





    public function actionPostPrintTransactions() {

        $searchModel = new PostPrintTransactionsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('post-print-transactions',[
                'searchModel'=> $searchModel,
                'dataProvider' => $dataProvider,
            ]);



    }


    public function actionPrintView($id) {
        $badgeModel = Badges::findOne($id);
        $content = $this->renderPartial('_badge-print-view',['model'=>$badgeModel]);
        
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_BLANK, 
            // A4 paper format
            'format' => Pdf::FORMAT_A4, 
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT, 
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER, 
            // your html content input
            'content' => $content, 
            'marginTop'=>0,
            'marginLeft'=>0,
            'marginRight'=>0,
            'marginBottom'=>0,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting 
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}', 
             // set mPDF properties on the fly
            'options' => ['title' => 'AGC Range Badge'],
             // call mPDF methods on the fly
            'methods' => [ 
                'SetHeader'=>['Powered By itekk.us'], 
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);
        
        // return the pdf output as per the destination setting
        return $pdf->render(); 
    }

    public function actionGetFamilyBadges() {

        
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $clubId = $parents[0];
                $familyBadges = Badges::find()->where(['club_id'=>$clubId])->all();
                $familyBadgesList = ArrayHelper::map($familyBadges, 'badge_number','first_name');

                $array = [];

                foreach ($familyBadges as  $value) {
                    $array [] = [
                        'id' => $value->badge_number,
                        'name' => $value->badge_number.' - '.$value->first_name,
                    ];
                }

                echo Json::encode(['output'=>$array, 'selected'=>'']);
                return;
            }
        }
        echo Json::encode(['output'=>'', 'selected'=>'']);
    }

    public function actionIndex()
    {
        $searchModel = new BadgesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Badges model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    public function actionViewWorkCredits($id) {
        $searchModel = new WorkCreditsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['badge_number'=>$id]);
        $dataProvider->pagination->pageSize = 20;

        return $this->render('view-work-credits',[
                'model'=>$this->findModel($id),
                'searchModel'=>$searchModel,
                'dataProvider'=>$dataProvider,
        ]);
    }

    public function actionViewSubscriptions($id) {

        $model = $this->findModel($id);
        $subciptionsArray = BadgeSubscriptions::findOne($model->badge_subscription_id);
        return $this->render('view-subscriptions',[
                'model'=>$this->findModel($id),
                'subciptionsArray'=>$subciptionsArray,
            ]);
    }

    /**
     * Creates a new Badges model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

    public function actionRenewMembership($membership_id) {
        $model = new BadgeSubscriptions();

        $badgeRecords = Badges::findOne($membership_id);
        $paymentArray = FeesStructure::find()->where([
                            'membership_id'=>$badgeRecords->badge_type,
                            'type'=>'badge_fee',
                            'status'=>'0'
                        ])->one();
        
        if ($model->load(Yii::$app->request->post())) {
                
                $model->valid_from = date('Y-m-d',strtotime($this->getNowTime()));
                $model->valid_true = date('Y-m-d',strtotime($model->expires));
                $model->status = 'active';
                $model->created_at = $this->getNowTime();
                $model->badge_fee = $model->badge_fee;
                $model->paid_amount = $model->badge_fee - $model->discount;
                //echo'<pre>'; print_r($model); die();
                $model->transaction_type = $model->redeemable_credit>0 ? 'CERT' : 'RENEW';
                $model->club_id = $badgeRecords->club_id;
                //echo'<pre>'; print_r($model->transaction_type); die();
                if($model->save()) {
                    $tempSubcriptionId = $badgeRecords->badge_subscription_id;
                    $badgeRecords->expires = $model->valid_true;
                    $badgeRecords->work_credits = $badgeRecords->work_credits - $model->redeemable_credit;
                    $badgeRecords->badge_subscription_id = $model->id;
                    $badgeRecords->sticker = $model->sticker;
                    if($model->redeemable_credit>0) {

                        $workCreditTransactions = new WorkCreditTransactions();
                        $workCreditTransactions->badge_number = $badgeRecords->badge_number;

backend/views/badges/_credit-table-view.php
<?php
 

?>

<tr>
    <td><?=$model->project_name?></td>
	<td><?=date('M d, Y',strtotime($model->work_date))?></td>
	<td><?=$model->authorized_by?></td>
	<td><?= $model->work_hours?></td>
</tr>

backend/views/badges/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\DatePicker;
use kartik\widgets\DepDrop;
use yii\helpers\Url;
use kartik\money\MaskMoney;

/* @var $this yii\web\View */
/* @var $model backend\models\Badges */
/* @var $form yii\widgets\ActiveForm */
?>


<div class="badges-form">
<?php $form = ActiveForm::begin(); ?>
<div class="row">

    <div class="col-xs-12 col-sm-8">
        <div class="row">
            <?php if(!$model->isNewRecord)  { ?>
            <div class="col-xs-12 col-sm-6">
                <?= $form->field($model, 'badge_number')->textInput(['readOnly'=>true]) ?>  
            </div>
            <?php } ?>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-2">
                <?= $form->field($model, 'prefix')->textInput(['readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
            <div class="col-xs-12 col-sm-4">
                <?= $form->field($model, 'first_name')->textInput(['readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
            <div class="col-xs-12 col-sm-4">
                <?= $form->field($model, 'last_name')->textInput(['readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
            <div class="col-xs-12 col-sm-2">
                <?= $form->field($model, 'suffix')->textInput(['readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
        </div>
        <div class="row">

            <div class="col-xs-12 col-sm-6">
                <?= $form->field($model, 'address')->textarea(['rows' => '3']) ?>
            </div>
            <div class="col-xs-12 col-sm-6">
                <?= $form->field($model, 'address_op')->textarea(['rows' => '3']) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <?= $form->field($model, 'city')->textInput(['readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
            <div class="col-xs-12 col-sm-2">
                <?= $form->field($model, 'state')->textInput(['readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
            <div class="col-xs-12 col-sm-2">
                <?= $form->field($model, 'zip')->textInput([]) ?>
            </div>
            <div class="col-xs-12 col-sm-2">
                <?=  $form->field($model, 'gender')->radioList([ '0'=>'Male', '1'=> 'Female']) ?>
                
            </div>
            <div class="col-xs-12 col-sm-3">
                <?= $form->field($model, 'yob')->textInput(['maxlength'=>true]) ?>
                
            </div>
        </div>
        <div class="row">
            
            <div class="col-xs-12 col-sm-6">
                <?= $form->field($model, 'email')->textInput(['readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
            <div class="col-xs-12 col-sm-6">
                <?= $form->field($model, 'email_op')->textInput(['readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <?= $form->field($model, 'phone')->textInput(['maxlength'=>true,'readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
            <div class="col-xs-12 col-sm-6">
                <?= $form->field($model, 'phone_op')->textInput(['maxlength'=>true,'readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <?= $form->field($model, 'ice_contact')->textInput(['readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
            <div class="col-xs-12 col-sm-6">
                <?= $form->field($model, 'ice_phone')->textInput(['maxlength'=>true,'readonly'=> $model->isNewRecord ? false : true,]) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-8">
                <?php if($model->isNewRecord) { ?>
                <?= $form->field($model, 'club_name')->dropDownList($model->getClubNamesList(), ['prompt'=>'select','id'=>'club-id']); ?>
                <?php } else { ?>
                <?= $form->field($model, 'club_name')->textInput(['readonly' => true]) ?>
                <?php } ?>
            </div>
            <div class="col-xs-12 col-sm-4">

                <?= $form->field($model, 'club_id')->textInput(['readonly' => true]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <?= $form->field($model, 'mem_type')->dropDownList($model->getMemberShipList(),['prompt'=>'select']) ?>
            </div>
            <div class="col-xs-12 col-sm-3">
                <?= $form->field($model, 'badge_type')->textInput(['readonly' => true ])->label('Membership ID') ?>
            </div>
            
            <div class="col-xs-12 col-sm-3">
                <?= $form->field($model, 'incep')->textInput(['readonly' => true,'value'=>date('M d, Y h:i A')]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-3" ng-if="membershipType=='2'">

           
            </div>
        </div>

            <?= $form->field($model, 'primary')->widget(DepDrop::classname(), [
                'type'=>DepDrop::TYPE_SELECT2,
                'options'=>['id'=>'primary-id'],
                'pluginOptions'=>[
                    'depends'=>['club-id'],
                    'placeholder'=>'Select...',
                    'url'=>Url::to(['/badges/get-family-badges'])
                ]
            ]);
            ?>



        <div class="row">

            <?php 
                $month =date('m');
                if($month<=10) {
                    $date = date('30-01-Y', strtotime('+1 year'));
                }
                else {
                    $date = date('30-01-Y', strtotime('+2 year'));
                }

             ?>
            <div class="col-xs-12 col-sm-3">
                <?= $form->field($model, 'expires')->textInput(['readonly' => true,'value'=> date('M d, Y',strtotime($date)) ]) ?>
            </div>
             <div class="col-xs-12 col-sm-3">
                <?= $form->field($model, 'wt_date')->textInput(['value'=>date('M d, Y') ]) ?>
            </div>
             <div class="col-xs-12 col-sm-6">
                <?= $form->field($model, 'wt_instru')->textInput([]) ?>
            </div>
        </div>
        <div class="row">
                <div class="col-xs-12 col-sm-12">
                <?= $form->field($model, 'remarks')->textarea(['rows' => '4']) ?>
                <div class="form-group">
                    <?= Html::submitButton($model->isNewRecord ? '<i class="fa fa-save"> </i> SAVE' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                    <?= Html::a('<i class="fa fa-eraser"> </i> Clear',['/badges/create'],['class' => 'btn btn-danger']) ?>
                </div> 
            </div>

        </div>
    
    </div>

    <div class="col-xs-12 col-sm-4">
        <div class="row">
            <div class="summary-block-payment box">
                <div class="col-xs-12 col-sm-12">

                    <?= $form->field($model, 'badge_fee')->widget(MaskMoney::classname(), [

                        'pluginOptions' => [
                        'allowNegative' => false,
                        ]
                    ]); ?>
                   
                </div>
                <div class="col-xs-12 col-sm-12">

                <?= $form->field($model, 'discounts')->widget(MaskMoney::classname(), [
                        
                        'pluginOptions' => [
                        'allowNegative' => false,
                        ]
                    ]); ?>

                </div>
                <div class="col-xs-12 col-sm-12">
                    <?= $form->field($model, 'amt_due')->widget(MaskMoney::classname(), [
                        
                        'pluginOptions' => [
                        'allowNegative' => false,
                        ]
                    ]); ?>
                   
                </div>
                <div class="col-xs-12 col-sm-12">
                    <?= $form->field($model, 'payment_method')->dropDownList(['cash'=>'Cash','check'=>'Check','credit'=>'Credit Card','online'=>'Online','other'=>'Other'],['prompt'=>'select']) ?>
                </div>

                 <div class="col-xs-12 col-sm-12">
                    <?= $form->field($model, 'sticker')->textInput(['maxlength'=>true]) ?>
                </div>
                <div class="clearfix"></div>
            </div>
            

        </div>
    </div>
    
</div>  
<?php ActiveForm::end(); ?>
</div>

backend/views/badges/_search.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\daterange\DateRangePicker;

/* @var $this yii\web\View */
/* @var $model backend\models\search\BadgesSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="row">
    <div class="col-xs-12">
        <h3> Filters <h3>
    </div>
</div>

<div class="row">

    <div class="badges-search">
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
    <div class="col-sm-6">
<!-- 
<?=  $form->field($model, 'expire_date_range', [
    'options'=>['class'=>'drp-container form-group']
    ])->widget(DateRangePicker::classname(), [
    'presetDropdown'=>true,
    'hideInput'=>true,
    'pluginOptions' => [
            'locale'=>[
            'format'=>'MM/DD/YYYY',
        ],
        'opens'=>'left'
        ],
    ]); ?>
  -->

    <?= $form->field($model, 'expire_condition')->dropDownlist(['active'=>'Active','active+2'=>'Active +2','expired<2'=>'Expired <2','expired>2'=>'Expired >2','inactive'=>'Inactive','all'=>'All'],['value'=>$model->expire_condition !=null ? $model->expire_condition : 'active+2'])->label('Expire Type') ?>

    </div>
    <div class="col-sm-6">
        <div class=" form-group btn-group pull-right">
            <?= Html::submitButton('<i class="fa fa-search" aria-hidden="true"></i> Search', ['class' => 'btn btn-primary']) ?>
            <?= Html::a('<i class="fa fa-eraser" aria-hidden="true"></i> Reset', ['/badges/index'],['class' => 'btn btn-danger']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
    

</div>
</div>

backend/views/badges/_subsciption.php
<?php 
use yii\helpers\Html;
use backend\models\BadgeSubscriptions;

$subciptionsArray = BadgeSubscriptions::findOne($model->badge_subscription_id);
//echo'<pre>'; print_r($subciptionsArray); 
?>


<div class="col-xs-12 col-sm-8">
    <div class="item panel panel-default"><!-- widgetBody -->
        <div class="panel-heading">
            <h3 class="panel-title pull-left"> Subscriptions Details</h3>
            <div class="pull-right">
                <div class="btn-group pull-right">
                    <?= Html::a('Renew Membership', ['/badges/renew-membership', 'membership_id' =>$model->badge_number], [
                    'class' => 'btn btn-primary',
                    'data' => [
                        'confirm' => 'Are you sure you want to Renew Membership',
                        'method' => 'post',
                    ],
               		]) ?>                  
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="panel-body">
           <div class="clients-view">
                <table id="w0" class="table table-striped table-bordered detail-view">
                	<tbody>
                		<tr>
							<th>Badge Number</th>
							<td><?=$subciptionsArray->badge_number?></td>
						</tr>
                		<tr>
							<th>Membership Status</th>
							<td><?php 
								if($subciptionsArray->status=='active') echo'<span class="label label-success"> '.ucfirst($subciptionsArray->status).' </span>';
								else if ($subciptionsArray->status=='expired') echo'<span class="label label-warning">'.ucfirst($subciptionsArray->status).'</span>';
							 ?></td>
						</tr>
						<tr>
							<th>Expire Date</th>
							<td><?=date('M d, Y',strtotime($subciptionsArray->valid_true))?></td>
						</tr>
						<tr>
							<th>Membership renewed on</th>
							<td><?=date('M d, Y H:i A',strtotime($subciptionsArray->created_at))?></td>
						</tr>
						<tr>
							<th>Payment Type</th>
							<td><?=ucfirst($subciptionsArray->payment_type)?></td>
						</tr>
						<tr>
							<th>Badge Fee</th>
							<td> <?=money_format('%i', $subciptionsArray->badge_fee);?> </td>
						</tr>
						<tr>
							<th>Discount ( if any ) </th>
							<td> <?=money_format('%i', $subciptionsArray->discount);?> </td>
						</tr>
						<tr>
							<th>Paid Amount</th>
							<td> <?=money_format('%i', $subciptionsArray->paid_amount);?> </td>
						</tr>
						
						
					</tbody>
				</table>
            </div>
        </div>
    </div>
</div>

backend/views/badges/post-print-transactions.php
<?php
use backend\models\Badges;
use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\widgets\ActiveForm;
use kartik\widgets\DatePicker;

use kartik\export\ExportMenu;
use kartik\grid\GridView;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\ClubsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Post Print Transactions - '.date('M d, Y',strtotime(yii::$app->controller->getNowTime()));
$this->params['breadcrumbs'][] = ['label' => 'Admin Function', 'url' => ['/badge/admin-function']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="clubs-index">
    <div class="row">

        <div class="col-xs-12">
            <h2><?= Html::encode($this->title) ?></h2>
           
        </div>
        <div class="col-xs-8">
        </div>
        <div class="col-xs-4">
             <?php $form = ActiveForm::begin([
                'id'=>'postPrintTransactionForm',
                'action' => ['/badges/post-print-transactions'],
                'method' => 'get',
            ]); ?>


           
            <!-- <div class="form-group">
                <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
                <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
            </div> -->

            <?php echo $form->field($searchModel, 'created_at')->widget(DatePicker::classname(), [
                'options' => ['placeholder' => 'Transaction Date'],
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'mm/dd/yyyy'
                ]
            ])->label('Transaction Date') ?>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
    <div class="row">
      
        <div class="col-xs-12">
            <?php 

                $gridColumns = [
                    //['class' => 'kartik\grid\SerialColumn'],
                    [
                        'header'=>'Badge Number',
                        'value' => 'badge_number',
                        'contentOptions' => ['class' => 'text-left'],
                    ],
                    [
                        'header'=>'Transaction Type',
                        'value' => 'transaction_type',
                    ],
                    [
                        'header'=> 'Name',
                        'value' => function($model) {
                            $badgeArry = Badges::findOne($model->badge_number);
                            return $badgeArry->prefix.' '.$badgeArry->first_name.' '.$badgeArry->last_name.' '.$badgeArry->suffix;
                        },
                    ],
                    [
                        'header'=>'Club',
                        'value'=>'clubDetails.club_name',
                    ],
                    [
                        'header'=>'Fee',
                        'value'=>function($model) {
                             return money_format('$%i', $model->badge_fee);
                        },
                        'contentOptions' => ['class' => 'text-right'],
                    ],
                    [
                        'header'=>'Paid Amount',
                        'value'=>function($model) {
                             return money_format('$%i', $model->paid_amount);
                        },
                        'contentOptions' => ['class' => 'text-right'],
                    ],
                    
                   
                   
                    
                   
                ];

                echo ExportMenu::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => $gridColumns,
                    'fontAwesome' => true,
                    'batchSize' => 10,
                    'filename'=>  $this->title,
                    'target' => '_blank',
                    'folder' => '@webroot/export', // this is default save folder on server
                ]) . "<hr>\n".
                GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => $gridColumns,
                ]);
                     
            ?>
        </div>
       
    </div>
</div>