backend/models/WorkCredits.php
<?php

namespace backend\models;

use Yii;
use backend\models\Badges;
use yii\helpers\ArrayHelper;
/**
 * This is the model class for table "work_credits".
 *
 * @property integer $id
 * @property integer $badge_number
 * @property string $work_date
 * @property double $work_hours
 * @property string $project_name
 * @property string $remarks
 * @property string $authorized_by
 * @property string $status
 * @property string $updated_at
 */
class WorkCredits extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $badge_holder_name;
    public $work_hours_new;

    public static function tableName()
    {
        return 'work_credits';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['badge_number', 'work_hours', 'project_name', 'authorized_by', 'status', 'updated_at','created_role'], 'required'],
            [['badge_number'], 'integer'],
            [['work_date', 'updated_at','work_hours_new','created_role'], 'safe'],
            [['work_hours'], 'number'],
	    [['remarks'],'safe'],
            [['remarks', 'status'], 'string'],
            [['project_name', 'authorized_by'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'badge_number' => 'Badge Number',
            'work_date' => 'Work Date',
            'work_hours' => 'Work Hours',
            'project_name' => 'Project Name',
            'remarks' => 'Remarks',
            'authorized_by' => 'Autherized By',
            'status' => 'Status',
            'updated_at' => 'Updated At',
            'work_hours_new'=>'Work Hours',
        ];
    }

    public function getBadgeNumbers() {
        
        $badgesArray = Badges::find()->where(['status'=>'active'])->all();
        $badgesList = ArrayHelper::map($badgesArray,'badge_number','badge_number');
        return $badgesList;
    }       
}

backend/controllers/BadgeController.php
<?php

namespace backend\controllers;

use backend\controllers\SiteController;
use kartik\mpdf\Pdf;

class BadgeController extends SiteController
{	
    public function actionBadgePrintView() {
    // get your HTML raw content without any layouts or scripts
        //return $this->render('badge-print-view');
        $content = $this->renderPartial('_badge-print-view');
        
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_BLANK, 
            // A4 paper format
            'format' => Pdf::FORMAT_A4, 
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT, 
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER, 
            // your html content input
            'content' => $content, 
            'marginTop'=>0,
            'marginLeft'=>0,
            'marginRight'=>0,
            'marginBottom'=>0,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting 
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}', 
             // set mPDF properties on the fly
            'options' => ['title' => 'AGC Range Badge'],
             // call mPDF methods on the fly
            'methods' => [ 
                'SetHeader'=>['Powered By itekk.us'], 
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);
        
        // return the pdf output as per the destination setting
        return $pdf->render(); 
    }
    
	public function actionCreate() {
		$model = new \backend\models\Badges();
		return $this->render('_create',[
			'model' => $model
		]);
	}

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionUpdate()
    {
       $model = new \backend\models\Badges();
        return $this->render('_update',[
            'model' => $model
        ]);
    }

    public function actionAdminFunction() {

        return $this->render('adminMenu');
    }
    public function actionClubNameLookUp() {
        return $this->render('club-name-look-up');
    }
    public function actionClubNameCreate() {
        $model = new \backend\models\Badges();
        return $this->render('create-club-name',['model'=>$model]);
    }

    public function actionClubNameEdit() {
        $model = new \backend\models\Badges();
        return $this->render('edit-club-name',['model'=>$model]);
    }

    public function actionBrowsWorkCredits() {
        return $this->render('brows-credit');
    }

    public function actionWorkCreditMenu() {
        return $this->render('work-credit-menu');
    }

    public function actionWorkCreditTransfer() {

         $model = new \backend\models\Badges();
        return $this->render('work-credit-transfer',[
            'model' => $model
        ]);

        
    }

    public function actionWorkCreditEntry() {
        $model = new \backend\models\Badges();
        return $this->render('work-credit-entry',[
            'model' => $model
        ]);
         
    }


    public function actionUsersIndex() {

        return $this->render('users-index');
    }

    public function actionCreateUser() {
        $model = new \backend\models\Badges();
        return $this->render('create-user',[
            'model' => $model
            ]);
    }

    public function actionEditUser() {
        $model = new \backend\models\Badges();
        return $this->render('edit-user',[
            'model' => $model
            ]);
    }

     public function actionViewUser() {
        $model = new \backend\models\Badges();
        return $this->render('view-user',[
            'model' => $model
            ]);
    }


    





    

}

backend/controllers/WorkCreditsController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\WorkCredits;
use backend\models\search\WorkCreditsSearch;
use backend\models\CreditTransferQueue;
use backend\models\WorkCreditTransactions;
use backend\models\search\CreditTransferQueueSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\controllers\SiteController;
use backend\models\Badges;

/**
 * WorkCreditsController implements the CRUD actions for WorkCredits model.
 */
class WorkCreditsController extends SiteController
{
    /**
     * @inheritdoc
     */
    public $enableCsrfValidation = false;

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all WorkCredits models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new WorkCreditsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->orderBy(['id' => SORT_DESC]);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single WorkCredits model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new WorkCredits model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

    public function actionStickyForm($type) {
        if($type=='true') {
            $session = Yii::$app->session;
            $session->set('stickyForm', 'true');
            $responce = [
                'status'=>true,
            ];

            return json_encode($responce,true);
        }
        else if($type=='false') {
            $session = Yii::$app->session;
            $session->set('stickyForm', 'false');
            $responce = [
                'status'=>false,
            ];

            return json_encode($responce,true);
        }
    }

    public function actionImport() {
        if(yii::$app->request->post()) {
            $activeUser = $this->getActiveUser();
            ini_set('memory_limit', '-1');
            ini_set('max_execution_time',6000000000);
            $workCredits = $_FILES['file']['tmp_name'];
            $objPHPExcel = new \PHPExcel();
            $items = Excel::import($workCredits);
            $errorArrayNotExist = [];
            $corrupted = [];
            $successful = 0;
            foreach ($items as $key => $item) {
                if(isset($item['badgenum']) && $item['badgenum']!=null) {
                    $isExist = $this->badgeIsExist($item['badgenum']);
                    if($isExist==true) {
                        $workCreditsModel = new WorkCredits();
                        $workCreditsModel->badge_number = $item['badgenum'];
                        $workCreditsModel->work_date = date('Y-m-d',strtotime($item['workdate']));
                        $workCreditsModel->work_hours = $item['workhours'];
                        $workCreditsModel->project_name = $item['project'];
                        $workCreditsModel->status = '0';
                        $workCreditsModel->remarks = $item['remarks']!=null ? $item['remarks']: '-blank-';
                        $workCreditsModel->authorized_by = $item['who'];
                        $workCreditsModel->created_at = $this->getNowTime();
                        $workCreditsModel->updated_at = $this->getNowTime();
                        $workCreditsModel->created_role = $activeUser->privilege;
                        if($workCreditsModel->save()) {
                            $badge = Badges::findOne($workCreditsModel->badge_number);
                            $badge->work_credits = $badge->work_credits + $workCreditsModel->work_hours;
                            if($badge->save(false)) {
                                $workCreditsModel->status = '1';
                                $workCreditsModel->save();
                                $workCreditTransactions = new WorkCreditTransactions();
                                $workCreditTransactions->badge_number = $workCreditsModel->badge_number;
                                $workCreditTransactions->type = 'debit';
                                $workCreditTransactions->value = $workCreditsModel->work_hours;
                                $workCreditTransactions->remarks = 'Work Credit Add - '.$workCreditsModel->remarks;
                                $workCreditTransactions->created_at = $this->getNowTime();
                                $workCreditTransactions->updated_at = $this->getNowTime();
                                $workCreditTransactions->work_credits_id = $workCreditsModel->id;
                                if($workCreditTransactions->save()) {

                                }
                             }
                        $successful++;

                        }
                    }
                    else {
                        $errorArrayNotExist [] = $item;
                    }

                }
                else {
                    $corrupted [] = $item;
                }
                
            }

            $responce = [
                'errorArrayNotExist' => count($errorArrayNotExist),
                'corrupted' => count($corrupted),
                'successful' => $successful,
            ];

            return json_encode($responce,true);

        }
        else {
            return $this->render('import-form',[
            ]);
        }
    }


    public function actionCreate()
    {   
        $model = new WorkCredits();

        

        if ($model->load(Yii::$app->request->post())) {

            $session = Yii::$app->session;
            $sticky = $session->get('stickyForm');
            if($sticky=='true') {
                $stickyData = [
                    'work_date'=> date('Y-m-d',strtotime($model->work_date)),
                    'authorized_by' => $model->authorized_by,
                    'work_hours' => $model->work_hours,
                    'project_name' => $model->project_name,
                    'remarks' => $model->remarks,

                ];
                $session->set('stickyData',$stickyData);
            }

            else if($sticky=='false') {
               $stickyData = [];
               $session->set('stickyData',$stickyData);
            }

            $activeUser = $this->getActiveUser();
            $model->work_date = date('Y-m-d',strtotime($model->work_date));
            $model->status = '0';
            $model->created_at = $this->getNowTime();
            $model->updated_at = $this->getNowTime();
            $model->created_role = $activeUser->privilege;
            if($model->save()) {
                 $badge = Badges::findOne($model->badge_number);
                 $badge->work_credits = $badge->work_credits + $model->work_hours;
                 if($badge->save(false)) {
                    $model->status = '1';
                    $model->save();
                    $workCreditTransactions = new WorkCreditTransactions();
                    $workCreditTransactions->badge_number = $model->badge_number;
                    $workCreditTransactions->type = 'debit';
                    $workCreditTransactions->value = $model->work_hours;
                    $workCreditTransactions->remarks = 'Work Credit Add - '.$model->remarks;
                    $workCreditTransactions->created_at = $this->getNowTime();
                    $workCreditTransactions->updated_at = $this->getNowTime();
                    $workCreditTransactions->work_credits_id = $model->id;
                    if($workCreditTransactions->save()) {

                    }
                 }
                Yii::$app->getSession()->setFlash('success', 'Work Credit has been added');
                $sticky = $session->get('stickyForm');
                if($sticky=='true') {
                    return $this->redirect(['/work-credits/create']);
                }
                else if($sticky=='false') {
                 return $this->redirect(['view', 'id' => $model->id]);   
                }
                
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } 
        else {



            if(isset($_GET['badge_number'])) {
                $badgeArray = Badges::findOne($_GET['badge_number']);

            }
            else {
                $badgeArray = null;
            }

            return $this->render('create', [
                'model' => $model,
                'badgeArray' =>$badgeArray,
            ]);
        }
    }

    /**
     * Updates an existing WorkCredits model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $activeUser = $this->getActiveUser();
            $badge = Badges::findOne($model->badge_number);
            $badge->work_credits = $badge->work_credits - $model->work_hours;
            if($badge->save(false)) {
                $model->work_hours = $model->work_hours_new;
                $model->work_date = date('Y-m-d',strtotime($model->work_date));
                $model->updated_at = $this->getNowTime();
                $model->created_role = $activeUser->privilege;
                if($model->save()) {

                    $workCreditTransactions =WorkCreditTransactions::find()->where(['work_credits_id'=>$model->id])->one();

backend/views/work-credits/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\WorkCreditsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="work-credits-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'badge_number') ?>

    <?= $form->field($model, 'work_date') ?>

    <?= $form->field($model, 'work_hours') ?>

    <?= $form->field($model, 'project_name') ?>

    <?php // echo $form->field($model, 'remarks') ?>

    <?php // echo $form->field($model, 'autherized_by') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/work-credits/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\WorkCredits */

$this->title = 'Create Work Credit';
$this->params['breadcrumbs'][] = ['label' => 'Admin Function', 'url' => ['/badge/admin-function']];
$this->params['breadcrumbs'][] = ['label' => 'Work Credits', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="work-credits-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'badgeArray'=>$badgeArray,
    ]) ?>

</div>

backend/views/work-credits/credit-transfer.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\WorkCreditsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Pending Requests';
$this->params['breadcrumbs'][] = ['label' => 'Admin Function', 'url' => ['/badge/admin-function']];
$this->params['breadcrumbs'][] = ['label' => 'Credit Transfer', 'url' => ['/work-credits/transfer-form']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="work-credits-index">
    <div class="row">
        <div class="col-xs-12">
             <?= $this->render('_view-tab-menu',[]) ?>
        </div>
        <div class="col-xs-12">
               
            <p> <?= Html::a('<i class="fa fa-plus"> </i> New Transfer Request', ['/work-credits/transfer-form'], ['class' => 'btn btn-success pull-right']) ?> </p>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    //['class' => 'yii\grid\SerialColumn'],

                    //'id',
                    'from_badge_number',
                    'to_badge_number',
                    [
                        'attribute'=>'work_hours',
                        'contentOptions' => ['class' => 'text-right'],
                    ],
                    
                    'status' => [   'header'=>'Status',
                            'value' =>function($model) {
                                if($model->status=='init') {
                                    return 'Waiting';
                                }
                                else if ($model->status=='success') {
                                    return 'Success';
                                }
                                else if ($model->status=='rejected') {
                                    return 'Rejected';
                                }
                                else if ($model->status=='pending') {
                                    return 'Pending';
                                }
                            },

                            'filter' => \yii\helpers\Html::activeDropDownList($searchModel, 'status', ['init' => 'Init', 'success' => 'Success','rejected'=>'rejected','pending'=>'Pending'],['class'=>'form-control','prompt' => 'All']),
                    ],
                    //'approved_by',
                    [
                        'header'=>'Created At',
                        'value'=> function($model) {
                            return date('M d, Y h:i A',strtotime($model->created_at));
                        },
                    ],
                   
                   [
                    'header'=>'Action',
                   'class' => 'yii\grid\ActionColumn',
                          'template'=>'{view}',
                            
                            'buttons'=>[

                                    'view' => function($url,$model) {
                                    return  Html::a(' View <span class="glyphicon glyphicon-eye-open"></span> ', ['/work-credits/transfer-view','request_id'=>$model->id], [
                                            'data-toggle'=>'tooltip',
                                            'data-placement'=>'top',
                                            'title'=>'View',
                                        ]); 

                                },
                            ]                            
                    ],
                    
                ],
            ]); ?>
        </div>
    </div>

    
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

   
    
</div>

backend/views/work-credits/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\WorkCreditsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Work Credits';
$this->params['breadcrumbs'][] = ['label' => 'Admin Function', 'url' => ['/badge/admin-function']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="work-credits-index">
    <div class="row">
        <div class="col-xs-12">
            <h1><?= Html::encode($this->title) ?></h1>   
            <div class="btn-group pull-right"> <?= Html::a('Create Work Credit', ['create'], ['class' => 'btn btn-success ']) ?>
             <?= Html::a('Import', ['/work-credits/import'], ['class' => 'btn btn-primary pull-right pull-right']) ?> 
            </div>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    //['class' => 'yii\grid\SerialColumn'],

                    //'id',
                    'badge_number',
                    [
                        'header'=>'Work Date',
                        'attribute'=>'work_date',
                        'value'=>function($model) {
                            return date('M d, Y',strtotime($model->work_date));
                        },
                    ],
                    'project_name',
                    [
                        'attribute'=>'work_hours',
                        'contentOptions' => ['class' => 'text-right'],
                    ],
                    [
                        'header'=>'Auth',
                        'attribute'=>'authorized_by',
                        'value'=> 'authorized_by',
                    ],

                    'status' => [   'header'=>'Status',
                            'value' => function($model, $attribute){ if($model->status==1) {return 'BULK IMP';} else if($model->status==0) {return 'Inactive';} },
                            'filter' => \yii\helpers\Html::activeDropDownList($searchModel, 'status', ['0' => 'BULK IMP', '1' => 'Inactive'],['class'=>'form-control','prompt' => 'All']),
                    ],
                    'remarks',
                    [
                        'header'=>'Procdate',
                        'attribute'=>'updated_at',
                        'value'=> function ($model) {
                                return date('M d, Y',strtotime(($model->updated_at)));
                        },
                    ],

                    [
                        'header'=>'Who',
                        'attribute'=>'created_role',
                        'value'=>function($model) {
                            if($model->created_role==1) {
                                return 'Admin';
                            }
                        },
                    ],

                    // 'remarks:ntext',
                    // 'authorized_by',
                    // 'status',
                    // 'updated_at',

                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>
        </div>
    </div>

    
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

   
    
</div>

backend/views/work-credits/transfer-form.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use kartik\select2\Select2;
use kartik\date\DatePicker;

$this->title = 'Credit Transfer form';
$this->params['breadcrumbs'][] = ['label' => 'Admin Function', 'url' => ['/badge/admin-function']];
$this->params['breadcrumbs'][] = ['label' => 'Credit Transfer', 'url' => ['/work-credits/credit-transfer','type'=>'init']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="work-transfer-form" ng-controller="WorkTransferForm">
	<?php $form = ActiveForm::begin(); ?>
	<div class="row">
		<div class="col-xs-12">
		<h3> Transfer From </h3>
		</div>
		<div class="col-xs-4">
			<?= $form->field($model, 'from_badge_number')->widget(Select2::classname(), [
                    'data' => $WorkCreditsModel->getBadgeNumbers(),
                    'options' => ['placeholder' => 'Select a badge ...'],
                    'pluginOptions' => [
                        'allowClear' => true,

                    ],
                ]); ?>
		</div>
		<div class="col-xs-4">
			<?= $form->field($model, 'from_badge_name')->textInput(['readOnly'=>true]) ?>
		</div>

		<div class="col-xs-4">
			<div id="credit-block">
				<?= $form->field($model, 'total_credit_avl')->textInput(['readOnly'=>true]) ?>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
		<h3> Transfer To </h3>
		</div>
		<div class="col-xs-4">
			<?= $form->field($model, 'to_badge_number')->widget(Select2::classname(), [
                    'data' => $WorkCreditsModel->getBadgeNumbers(),
                    'options' => ['placeholder' => 'Select a badge ...'],
                    'pluginOptions' => [
                        'allowClear' => true,

                    ],
                ]); ?>

		</div>
		<div class="col-xs-4">
			<?= $form->field($model, 'to_badge_name')->textInput([]) ?>

		</div>

		<div class="col-xs-4">
			<?= $form->field($model, 'work_hours')->textInput([]) ?>
			
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-sm-8">
			<?= $form->field($model, 'note')->textArea(['rows'=>1]) ?>
		</div>
		<div class="col-xs-4">
			<?= $form->field($model, 'approved_by')->textInput(['maxlength'=>true]) ?>

			<div class="form-group">
       			<?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success pull-right' : 'btn btn-primary pull-right']) ?>
    		</div>
		</div>
		
	</div>

	<?php ActiveForm::end(); ?>  
</div>

backend/views/work-credits/transfer-view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\WorkCredits */

$this->title = 'Credit Transfer View';
$this->params['breadcrumbs'][] = ['label' => 'Admin Function', 'url' => ['/badge/admin-function']];
$this->params['breadcrumbs'][] = ['label' => 'Work Credits', 'url' => ['/work-credits/index']];
$this->params['breadcrumbs'][] = ['label' => 'Credit Transfer', 'url' => ['/work-credits/credit-transfer','type'=>'init']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="work-credits-view">

    

    <p>
      <?php if($model->status!='success') { ?>  
        <?= Html::a('Approve ', ['/work-credits/transfer-confirm', 'id' => $model->id], [
            'class' => 'btn btn-success',
            'data' => [
                'confirm' => 'Are you sure you want to approve ?',
                'method' => 'post',
            ],
        ]) ?>
        <?php } ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
        	[
        		'attribute'=>'work_hours',
        		'label' => 'Transfer Credit',
        	],
        	'frombadgeDetails.badge_number',
            'frombadgeDetails.first_name',
            'frombadgeDetails.last_name',
            'tobadgeDetails.badge_number',
            'tobadgeDetails.first_name',
            'tobadgeDetails.last_name',
            [
        		'attribute'=>'work_hours',
        		'label' => 'Issued on',
        		'value' => function($model) {
        			return date('M d, Y i:m A',strtotime($model->created_at));
        		},
        	],
        	[
        		'attribute'=>'status',
        		'label' => 'Status',
        		'value' => function($model) {
        			if($model->status=='init') {
        				return 'Waiting for Approval';
        			}
        			else if($model->status=='success') {
        				return 'Success';
        			}
        			else if($model->status=='rejected') {
        				return 'Rejected';
        			}
        			else if($model->status=='pending') {
        				return 'pending';
        			}
        		},
        	],
        	'note',
        	'adminUser.username',
        	'approved_by',
        	[
        		'attribute'=>'approved_at',
        		'label' => 'Approval Date',
        		'value' => function($model) {
        			if($model->approved_at!=null) {
        				return date('M d, Y i:m A',strtotime($model->approved_at));	
        			}
        			else {
        				return 'Not available';
        			}
        			
        		},
        	],

            /*'badge_number',
            [    
                'attribute'=>'work_date',
                'value'=>function($model,$attribute) {
                    return date('M d, Y',strtotime($model->work_date));
                },
            ],
            'work_hours',
            'project_name',
            'remarks:ntext',
            'autherized_by',
            [
                'attribute'=>'created_at',
                'value'=> function($model, $attribute) {
                    return date('M d, Y h:i A', strtotime($model->created_at));
                },
            ],
            [
                'attribute'=>'updated_at',
                'value'=> function($model, $attribute) {
                    return date('M d, Y h:i A', strtotime($model->updated_at));
                },
            ],*/
        ],
    ]) ?>

</div>

backend/views/work-credits/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\WorkCredits */

$this->title = 'Update Work Credits: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Admin Function', 'url' => ['/badge/admin-function']];
$this->params['breadcrumbs'][] = ['label' => 'Work Credits', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="work-credits-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>